apiVersion: v1
kind: ConfigMap
metadata:
  name: ${KTX_APP_NAME}
data:
  application.yaml: |
    server:
      port: 8080

    spring:
      cloud:
        openfeign:
          client:
            config:
              frame-voice-client:
                url: http://frame-voice:8080
              frame-state-client:
                url: http://frame-state:8080
              frame-auth-client:
                url: http://frame-auth:8080
              frame-parties-chat-client:
                url: http://frame-parties:8080
              frame-parties-community-client:
                url: http://frame-parties:8080
              frame-parties-directory-client:
                url: http://frame-parties:8080
              frame-parties-message-client:
                url: http://frame-parties:8080
              frame-parties-role-client:
                url: http://frame-parties:8080
              frame-parties-voice-client:
                url: http://frame-parties:8080
